version: "3"
services:
  database:
    container_name: database-mysql
    image: mysql
    volumes:
      - "db-path:/var/lib/mysql/"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: dd
      MYSQL_USER: user_mysql
      MYSQL_PASSWORD: 321

  package_app:
    build:
      context: ./build_project
      dockerfile: Docker_build
    volumes:
      - "build-path:/home/docker_12/target/"
      - "property-path:/home/docker_12/WebContent/"

  production:
    build:
      context: ./prod
      dockerfile: Docker_prod
    volumes:
      - "build-path:/usr/local/tomcat/webapps/"
      - "property-path:/usr/local/tomcat/ROOT/"
    depends_on:
      - package_app
      - database
    ports:
      - "8080:8080"

volumes:
  build-path:
  db-path:
  property-path:
